Repository umijs/father, pull requests merged in 2019-06, with the labels that each got.

#6 feat: support transform /lib/ to /es/ for esm format with config.importLibToEs
  README.md
  src/babel.ts
  src/build.ts
  src/fixtures/build/babel-importLibToEs/.umirc.library.js
  src/fixtures/build/babel-importLibToEs/expected/es/index.js
  src/fixtures/build/babel-importLibToEs/expected/lib/index.js
  src/fixtures/build/babel-importLibToEs/node_modules/foo/es/foo.js
  src/fixtures/build/babel-importLibToEs/node_modules/foo/lib/foo.js
  src/fixtures/build/babel-importLibToEs/node_modules/foo/package.json
  src/fixtures/build/babel-importLibToEs/src/index.js
  src/fixtures/build/rollup-importLibToEs/.umirc.library.js
  src/fixtures/build/rollup-importLibToEs/expected/index.esm.js
  src/fixtures/build/rollup-importLibToEs/expected/index.js
  src/fixtures/build/rollup-importLibToEs/node_modules/foo/es/foo.js
  src/fixtures/build/rollup-importLibToEs/node_modules/foo/lib/foo.js
  src/fixtures/build/rollup-importLibToEs/node_modules/foo/package.json
  src/fixtures/build/rollup-importLibToEs/src/index.js
  src/getRollupConfig.ts
  src/importLibToEs.js
  src/rollup.ts
  src/schema.ts
  src/types.d.ts
Labels: pr(enhancement)

#9 feat: support extra externals for rollup mode with config.extraExternals
  README.md
  src/babel.ts
  src/fixtures/build/rollup-extraExternals/.fatherrc.js
  src/fixtures/build/rollup-extraExternals/expected/index.esm.js
  src/fixtures/build/rollup-extraExternals/package.json
  src/fixtures/build/rollup-extraExternals/src/index.js
  src/fixtures/build/target-node/.fatherrc.js
  src/fixtures/build/target-node/expected/index.esm.js
  src/fixtures/build/target-node/expected/index.js
  src/getRollupConfig.ts
  src/getUserConfig.ts
  src/rollup.ts
  src/schema.ts
  src/types.d.ts
  yarn.lock
Labels: pr(enhancement)

#14 refactor: ease troubleshooting while missing tsconfig.json in typescript based project
  src/build.ts
  src/doc.ts
Labels: pr(enhancement)

#20 feat: Support default `tsconfig.json` as template
  .gitignore
  src/babel.ts
  src/build.ts
  src/fixtures/build/babel-typescript-template/.umirc.library.js
  src/fixtures/build/babel-typescript-template/expected/es/index.d.ts
  src/fixtures/build/babel-typescript-template/expected/es/index.js
  src/fixtures/build/babel-typescript-template/expected/lib/index.d.ts
  src/fixtures/build/babel-typescript-template/expected/lib/index.js
  src/fixtures/build/babel-typescript-template/src/index.ts
  template/tsconfig.json
Labels: enhancement

#19 feat: support 404 fallback mechanism while deploy docs
  src/doc.ts
Labels: pr(enhancement)

#21 feat: support pre-commit config
  bin/father.js
  package.json
  src/preCommit.ts
  src/schema.ts
  src/types.d.ts
  template/.eslintrc.js
  template/.prettierrc
Labels: pr(enhancement)

#22 dep: upgrade rollup, autoprefixer, and etc
  package.json
  yarn.lock
Labels: pr(dependency)

#23 feat: Support Storybook doc type
  .gitignore
  bin/father.js
  package.json
  src/doc/doc.e2e.ts
  src/doc/doc.test.ts
  src/doc/docz-plugin-react-externals.ts
  src/doc/docz.ts
  src/doc/doczrc.ts
  src/doc/index.ts
  src/doc/storybook-generator.ts
  src/doc/storybook-webpack.ts
  src/doc/storybook.ts
  src/father.e2e.ts
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.doc/assets.json
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.doc/index.html
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.doc/static/js/app.045561ed43ba83ea5c9a.js
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.doc/static/js/button-index.b72f0559.js
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.doc/static/js/vendors.27f5d684.js
  src/fixtures/doc/config-theme/.doc/assets.json
  src/fixtures/doc/config-theme/.doc/index.html
  src/fixtures/doc/config-theme/.doc/static/js/app.b51d4aa76313865074da.js
  src/fixtures/doc/config-theme/.doc/static/js/readme.032bb26a.js
  src/fixtures/doc/config-theme/.doc/static/js/vendors.27f5d684.js
  src/fixtures/doc/css-modules/.doc/assets.json
  src/fixtures/doc/css-modules/.doc/index.html
  src/fixtures/doc/css-modules/.doc/static/css/button-index.78f78683149b477dcf58.css
  src/fixtures/doc/css-modules/.doc/static/js/app.78f78683149b477dcf58.js
  src/fixtures/doc/css-modules/.doc/static/js/button-index.a39b68e4.js
  src/fixtures/doc/css-modules/.doc/static/js/vendors.27f5d684.js
  src/fixtures/doc/normal/.doc/assets.json
  src/fixtures/doc/normal/.doc/index.html
  src/fixtures/doc/normal/.doc/static/css/button-index.781141635bf300e3d361.css
  src/fixtures/doc/normal/.doc/static/js/app.781141635bf300e3d361.js
  src/fixtures/doc/normal/.doc/static/js/button-index.a6cd106e.js
  src/fixtures/doc/normal/.doc/static/js/readme.6cdfd92f.js
  src/fixtures/doc/normal/.doc/static/js/vendors.27f5d684.js
  template/tsconfig.json
Labels: pr(enhancement)

#25 refactor: remove warning from unit test
  src/doc/index.ts
  src/fixtures/build/babel-extra-babel-presets-and-plugins/.fatherrc.js
  src/fixtures/build/babel-importLibToEs/.fatherrc.js
  src/fixtures/build/babel-node-files/.fatherrc.js
  src/fixtures/build/babel-normal/.fatherrc.js
  src/fixtures/build/babel-syntax/.fatherrc.js
  src/fixtures/build/babel-typescript-disable-typecheck/.fatherrc.js
  src/fixtures/build/babel-typescript-template/.fatherrc.js
  src/fixtures/build/babel-typescript/.fatherrc.js
  src/fixtures/build/lerna-root-config/.fatherrc.js
  src/fixtures/build/lerna/packages/bar/.fatherrc.js
  src/fixtures/build/lerna/packages/foo/.fatherrc.js
  src/fixtures/build/require-node_modules-in-sub-directory/.fatherrc.js
  src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/package.json
  src/fixtures/build/rollup-commonjs-deps-named-exports/.fatherrc.js
  src/fixtures/build/rollup-commonjs-deps/.fatherrc.js
  src/fixtures/build/rollup-config-alias/.fatherrc.js
  src/fixtures/build/rollup-css-autoprefixer/.fatherrc.js
  src/fixtures/build/rollup-css-extract/.fatherrc.js
  src/fixtures/build/rollup-css-modules/.fatherrc.js
  src/fixtures/build/rollup-css/.fatherrc.js
  src/fixtures/build/rollup-esm-minify/.fatherrc.js
  src/fixtures/build/rollup-esm-mjs/.fatherrc.js
  src/fixtures/build/rollup-extra-babel-presets-and-plugins/.fatherrc.js
  src/fixtures/build/rollup-import-directory/.fatherrc.js
  src/fixtures/build/rollup-importLibToEs/.fatherrc.js
  src/fixtures/build/rollup-json/.fatherrc.js
  src/fixtures/build/rollup-less-modules/.fatherrc.js
  src/fixtures/build/rollup-less-node-modules/.fatherrc.js
  src/fixtures/build/rollup-less/.fatherrc.js
  src/fixtures/build/rollup-multiple-entry/.fatherrc.js
  src/fixtures/build/rollup-normal/.fatherrc.js
  src/fixtures/build/rollup-outputFilename-with-overrides/.fatherrc.js
  src/fixtures/build/rollup-replace/.fatherrc.js
  src/fixtures/build/rollup-resolve-jsx/.fatherrc.js
  src/fixtures/build/rollup-runtimeHelpers/.fatherrc.js
  src/fixtures/build/rollup-typescript/.fatherrc.ts
  src/fixtures/build/rollup-umd-auto-name/.fatherrc.js
  src/fixtures/build/rollup-umd-globals/.fatherrc.js
  src/fixtures/build/rollup-umd-name/.fatherrc.js
  src/fixtures/build/rollup-umd-overrides/.fatherrc.js
  src/fixtures/doc/babel-extra-babel-presets-and-plugins/.fatherrc.js
  src/fixtures/doc/config-theme/.fatherrc.js
  src/fixtures/doc/css-modules/.fatherrc.js
  src/fixtures/doc/normal/.fatherrc.js
Labels: pr(chore)

#26 feat: Integrate with `umi-test`
  bin/father.js
  package.json
  src/test.ts
Labels: pr(enhancement)

#27 feat: support convert svg to react component
  package.json
  src/fixtures/build/rollup-svgr/.umirc.library.js
  src/fixtures/build/rollup-svgr/dist/index.esm.js
  src/fixtures/build/rollup-svgr/expected/index.esm.js
  src/fixtures/build/rollup-svgr/package.json
  src/fixtures/build/rollup-svgr/src/index.jsx
  src/fixtures/build/rollup-svgr/src/menu.svg
  src/getRollupConfig.ts
  yarn.lock
Labels: pr(enhancement)

#29 fix: ignore pkg .DS_Store
  src/build.test.ts
  src/build.ts
  src/fixtures/build/lerna/packages/.DS_Store
Labels: pr(test)

#31 dep: update docz-theme-umi to 2.0.0
  package.json
Labels: pr(dependency)

#34 fix: build function export
  .gitignore
  jasmine.js
  jest.config.js
  package.json
  packages/father-build/lib/babel.js
  packages/father-build/lib/build.js
  packages/father-build/lib/build.test.js
  packages/father-build/lib/getBabelConfig.js
  packages/father-build/lib/getRollupConfig.js
  packages/father-build/lib/getUserConfig.js
  packages/father-build/lib/importLibToEs.js
  packages/father-build/lib/index.js
  packages/father-build/lib/normalizeBundleOpts.js
  packages/father-build/lib/normalizeBundleOpts.test.js
  packages/father-build/lib/registerBabel.js
  packages/father-build/lib/rollup.js
  packages/father-build/lib/schema.js
  packages/father-build/lib/schema.test.js
  packages/father-build/lib/types.d.js
  packages/father-build/lib/utils.js
  packages/father-build/yarn.lock
  packages/father/lib/doc/doc.e2e.js
  packages/father/lib/doc/doc.test.js
  packages/father/lib/doc/docz-plugin-react-externals.js
  packages/father/lib/doc/docz.js
  packages/father/lib/doc/doczrc.js
  packages/father/lib/doc/index.js
  packages/father/lib/doc/storybook-generator.js
  packages/father/lib/doc/storybook-webpack.js
  packages/father/lib/doc/storybook.js
  packages/father/lib/father.e2e.js
  packages/father/lib/index.js
  packages/father/lib/preCommit.js
  packages/father/lib/test.js
  packages/father/src/index.ts
  packages/father/test.js
  packages/father/yarn.lock
  yarn.lock
Labels: pr(bug)

#37 fix(babel-config): only use es module with runtime plugin while target is browser
  packages/father-build/src/getBabelConfig.ts
Labels: pr(bug)

#38 fix: browserFiles don't match in windows since the path problem
  packages/father-build/src/babel.ts
Labels: pr(bug)

#39 feat: support use root tsconfig.json for babel mode
  packages/father-build/src/babel.ts
  packages/father-build/src/build.test.ts
  packages/father-build/src/build.ts
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/.fatherrc.js
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/expected/bar/es/index.js
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/expected/bar/lib/index.js
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/expected/foo/es/index.js
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/expected/foo/lib/index.js
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/lerna.json
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/packages/bar/package.json
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/packages/bar/src/index.ts
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/packages/foo/package.json
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/packages/foo/src/index.ts
  packages/father-build/src/fixtures/build/lerna-root-tsconfig/tsconfig.json
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#40 fix: export problem with father and father-build
  packages/father-build/.npmignore
  packages/father-build/src/index.ts
  packages/father/.npmignore
  packages/father/bin/father.js
  packages/father/package.json
  packages/father/src/index.ts
  packages/father/test.js
Labels: pr(bug)

#44 fix: d.ts does not copy in babel mode
  packages/father-build/src/babel.ts
Labels: pr(bug)

#45 feat: support compile less in babel mode with opts.lessInBabelMode
  README.md
  packages/father-build/package.json
  packages/father-build/src/babel.ts
  packages/father-build/src/fixtures/build/babel-less-to-css/.fatherrc.js
  packages/father-build/src/fixtures/build/babel-less-to-css/expected/es/index.css
  packages/father-build/src/fixtures/build/babel-less-to-css/expected/lib/index.css
  packages/father-build/src/fixtures/build/babel-less-to-css/src/index.less
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
  packages/father-build/yarn.lock
Labels: pr(enhancement)

#46 feat: support specify node version with opts.nodeVersion
  README.md
  packages/father-build/src/babel.ts
  packages/father-build/src/fixtures/build/target-node-version/.fatherrc.js
  packages/father-build/src/fixtures/build/target-node-version/expected/es/index.js
  packages/father-build/src/fixtures/build/target-node-version/expected/lib/index.js
  packages/father-build/src/fixtures/build/target-node-version/src/index.js
  packages/father-build/src/getBabelConfig.ts
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#42 feat: support customizing rollup-plugin-typescript2
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/.fatherrc.ts
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/expected/index.esm.js
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/expected/index.js
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/expected/type/index.d.ts
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/src/index.ts
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/tsconfig.json
  packages/father-build/src/fixtures/build/rollup-typescript-declarationDir/typings.d.ts
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.test.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#49 fix: .umirc.library.json to .fatherrc.json
  packages/father/src/doc/docz.ts
  packages/father/src/doc/doczrc.ts
Labels: pr(bug)

#51 fix: typing
  packages/father-build/src/types.d.ts
  packages/father/index.d.ts
  packages/father/src/doc/index.ts
Labels: pr(bug)
