Repository umijs/father, pull requests merged in 2019-12, with the labels that each got.

#167 fix: build failed with lerna + typescript + watchmode
  packages/father-build/package.json
  packages/father-build/src/fixtures/build/babel-syntax/expected/index.esm.js
  packages/father-build/src/fixtures/build/config-array/expected/index.umd.js
  packages/father-build/src/fixtures/build/require-node_modules-in-sub-directory/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-commonjs-deps-named-exports/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-commonjs-deps/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-node-resolve/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-normal/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-outputFilename-with-overrides/expected/dva.bar.js
  packages/father-build/src/fixtures/build/rollup-outputFilename-with-overrides/expected/dva.foo.umd.js
  packages/father-build/src/fixtures/build/rollup-outputFilename-with-overrides/expected/dva.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-auto-name/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-css-extract-minFile/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-globals/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-name/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-overrides/expected/fetch.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-overrides/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-umd-sourcemap/expected/index.umd.js
  packages/father-build/src/getBabelConfig.ts
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/yarn.lock
  packages/father/yarn.lock
Labels: pr(bug)

#169 doc: escape angle brackets of "<head>" in README.md
  README.md
Labels: pr(documentation)

#178 dep: upgrade rollup-plugin-terser@5.1.3, fix security warning
  packages/father-build/package.json
  packages/father-build/yarn.lock
Labels: pr(dependency)
