Repository umijs/father, pull requests merged in 2019-09, with the labels that each got.

#96 feat: support multiple config in .fatherrc.js
  packages/father-build/src/build.ts
  packages/father-build/src/fixtures/build/babel-cjs-lazy/.fatherrc.js
  packages/father-build/src/fixtures/build/babel-cjs-lazy/expected/lib/foo.js
  packages/father-build/src/fixtures/build/babel-cjs-lazy/expected/lib/index.js
  packages/father-build/src/fixtures/build/babel-cjs-lazy/src/foo.js
  packages/father-build/src/fixtures/build/babel-cjs-lazy/src/index.js
  packages/father-build/src/fixtures/build/config-array/.fatherrc.js
  packages/father-build/src/fixtures/build/config-array/expected/index.umd.js
  packages/father-build/src/fixtures/build/config-array/expected/lib/index.js
  packages/father-build/src/fixtures/build/config-array/src/index.js
  packages/father-build/src/fixtures/build/config-array/ui/index.js
  packages/father-build/src/getUserConfig.ts
Labels: pr(enhancement)

#98 feat: support inject based on rollup-plugin-inject
  README.md
  packages/father-build/package.json
  packages/father-build/src/fixtures/build/rollup-inject/.fatherrc.js
  packages/father-build/src/fixtures/build/rollup-inject/expected/index.esm.js
  packages/father-build/src/fixtures/build/rollup-inject/package.json
  packages/father-build/src/fixtures/build/rollup-inject/src/index.js
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
  packages/father-build/yarn.lock
Labels: pr(enhancement)

#99 feat: support externalsExclude option
  README.md
  packages/father-build/src/fixtures/build/rollup-externalsExclude/.fatherrc.js
  packages/father-build/src/fixtures/build/rollup-externalsExclude/expected/index.esm.js
  packages/father-build/src/fixtures/build/rollup-externalsExclude/node_modules/foo/bar.js
  packages/father-build/src/fixtures/build/rollup-externalsExclude/node_modules/foo/package.json
  packages/father-build/src/fixtures/build/rollup-externalsExclude/package.json
  packages/father-build/src/fixtures/build/rollup-externalsExclude/src/index.js
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#100 fix: external problem with externalsExclude
  packages/father-build/src/fixtures/build/rollup-externalsExclude/.fatherrc.js
  packages/father-build/src/fixtures/build/rollup-externalsExclude/expected/index.js
  packages/father-build/src/fixtures/build/rollup-externalsExclude/node_modules/foo/index.js
  packages/father-build/src/getRollupConfig.ts
Labels: pr(bug)

#101 fix: close watcher for SIGINT
  packages/father-build/src/babel.ts
  packages/father-build/src/rollup.ts
Labels: pr(bug)

#103 chore: Add env for storybook usage
  packages/father/src/doc/storybook.ts
Labels: pr(chore)

#106 feat: add __test__ to babel ignore
  README.md
  packages/father-build/src/babel.ts
  packages/father-build/src/fixtures/build/babel-normal/src/__test__/__snapshots__/index.test.js.snap
  packages/father-build/src/fixtures/build/babel-normal/src/__test__/index.test.js
Labels: pr(enhancement)

#108 fix: don't transform fixtures and __test__ directory in babel mode
  packages/father-build/src/babel.ts
  packages/father-build/src/fixtures/build/babel-normal/src/fixtures/example/package.json
Labels: pr(bug)

#109 fix: ignore files in watch mode
  packages/father-build/src/babel.ts
Labels: pr(bug)

#110 feat: add include opt in rollup umd cjs use for project config
  README.md
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.test.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#111 feat: support extraRollupPlugins
  README.md
  packages/father-build/src/fixtures/build/rollup-extraRollupPlugins/.fatherrc.js
  packages/father-build/src/fixtures/build/rollup-extraRollupPlugins/expected/index.esm.js
  packages/father-build/src/fixtures/build/rollup-extraRollupPlugins/package.json
  packages/father-build/src/fixtures/build/rollup-extraRollupPlugins/src/index.js
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#114 fix: file encoding: gbk to utf-8
  packages/father-build/src/build.ts
Labels: pr(bug)

#116 fix(father): failed to resolve module in Windows
  packages/father/package.json
  packages/father/src/doc/storybook-generator.ts
Labels: pr(bug)
