Repository umijs/father, pull requests merged in 2019-07, with the labels that each got.

#54 fix(father-build): entry parse failed
  packages/father-build/bin/father-build.js
Labels: pr(bug)

#58 feat: Add reactConfig for udf react & reactDom url
  packages/father/src/doc/docz-plugin-react-externals.ts
Labels: pr(enhancement)

#60 dep: upgrade chokidar to 3.0.2 to fix windows problem
  packages/father-build/package.json
Labels: pr(dependency)

#62 dep: lodash version to 7.17.13
  packages/father-build/yarn.lock
  packages/father/package.json
  packages/father/yarn.lock
Labels: pr(dependency)

#76 feat: use COVERAGE env variable to control babel plugin babel-plugin-istanbul
  packages/father-build/package.json
  packages/father-build/src/getBabelConfig.ts
  packages/father/src/father.e2e.ts
Labels: pr(enhancement)

#77 feat: 配置文件支持传入 rollup-plugin-node-resolve 参数
  README.md
  packages/father-build/src/fixtures/build/rollup-node-resolve/.fatherrc.js
  packages/father-build/src/fixtures/build/rollup-node-resolve/expected/index.umd.js
  packages/father-build/src/fixtures/build/rollup-node-resolve/node_modules/foo/browser.js
  packages/father-build/src/fixtures/build/rollup-node-resolve/node_modules/foo/index.js
  packages/father-build/src/fixtures/build/rollup-node-resolve/node_modules/foo/package.json
  packages/father-build/src/fixtures/build/rollup-node-resolve/package.json
  packages/father-build/src/fixtures/build/rollup-node-resolve/src/index.js
  packages/father-build/src/getRollupConfig.ts
  packages/father-build/src/schema.test.ts
  packages/father-build/src/schema.ts
  packages/father-build/src/types.d.ts
Labels: pr(enhancement)

#79 fix: cjs babel do not use esm runtimeHelpers
  packages/father-build/src/fixtures/build/babel-runtimeHelpers/.fatherrc.js
  packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/es/index.js
  packages/father-build/src/fixtures/build/babel-runtimeHelpers/expected/lib/index.js
  packages/father-build/src/fixtures/build/babel-runtimeHelpers/package.json
  packages/father-build/src/fixtures/build/babel-runtimeHelpers/src/index.js
  packages/father-build/src/getBabelConfig.ts
  packages/father-build/src/getRollupConfig.ts
Labels: pr(bug)
